image: Ubuntu

cache:
  - node_modules

install:
  - nvm install 16.13.0
  - nvm use 16.13.0
  - npm install

test_script:
  - npm test -- --ci --watchAll=false

after_test:
  - npm run build

build: false

artifacts:
  - path: build\
    name: uibuild
