environment:
  nodejs_version: "6"

cache:
  - node_modules

install:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm test

build: off

artifacts:
  - path: build\
    name: uibuild