environment:
  nodejs_version: "6"
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: mEHmpM1N9cDrTrOpvxPtlfLYt8TgstG0TZu84on70/Tf34tWn2sER4Ys34MC1cVm

cache:
  - node_modules

install:
  - npm install
  - npm install coveralls --save-dev

test_script:
  - node --version
  - npm --version
  - npm test -- --coverage --coverageReporters=text-lcov > lcov.info
  - npm ./node_modules/coveralls/bin/coveralls.js < lcov.info
  - npm run build

after_test:


build: off

artifacts:
  - path: build\
    name: uibuild