environment:
  nodejs_version: "6"
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: mEHmpM1N9cDrTrOpvxPtlfLYt8TgstG0TZu84on70/Tf34tWn2sER4Ys34MC1cVm

cache:
  - node_modules

install:
  - npm install

test_script:
  - npm test -- --ci --watchAll=false

after_test:
  - npm run build

build: false

artifacts:
  - path: build\
    name: uibuild