environment:
  nodejs_version: "6"

cache:
  - node_modules

install:
  - npm install
  - npm install coveralls --save-dev

test_script:
  - node --version
  - npm --version
  - npm test -- --coverage --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js
  - npm run build

build: off

artifacts:
  - path: build\
    name: uibuild