environment:
  COVERALLS_REPO_TOKEN:
    secure: sq6fzsonRyN8gAzFIQjU+vgkkY0sb6YVwCRl9YaHcD4AuNyZCE1rHnjs8WFTq8oj

image: Ubuntu

cache:
  - node_modules

install:
  - nvm install 16.13.0
  - npm install

test_script:
  - npm test -- --ci --watchAll=false --coverage --coverageReporters=text-lcov > lcov.info

after_test:
  - node ./node_modules/coveralls/bin/coveralls.js < lcov.info
  - rm lcov.info
  - npm run build

build: off

artifacts:
  - path: build\
    name: uibuild
