const internalTestData = [
  {
    id: 1,
    name: 'New Character',
    completionStep: 1,
    str: 0,
    dex: 0,
    con: 0,
    int: 0,
    wis: 0,
    chr: 0,
    race: 'none',
    gender: 'n',
    height: 0,
    weight: 0,
    age: 0,
    className: 'none',
    alignment: 'none',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0
  },
  {
    id: 2,
    name: 'Gristle McThornbody',
    completionStep: 2,
    str: 10,
    dex: 10,
    con: 10,
    int: 10,
    wis: 10,
    chr: 10,
    race: 'none',
    gender: 'n',
    height: 0,
    weight: 0,
    age: 0,
    className: 'none',
    alignment: 'none',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0
  },
  {
    id: 3,
    name: 'Crunch Bonemeal',
    completionStep: 3,
    str: 10,
    dex: 10,
    con: 10,
    int: 10,
    wis: 10,
    chr: 10,
    race: 'Human',
    gender: 'M',
    height: 0,
    weight: 0,
    age: 0,
    className: 'none',
    alignment: 'none',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0,
    availableClasses: [
      'Fighter', 'Cleric', 'Mage', 'Rogue'
    ]
  },
  {
    id: 4,
    name: 'Rip Steakface',
    completionStep: 4,
    str: 10,
    dex: 10,
    con: 10,
    int: 10,
    wis: 10,
    chr: 10,
    race: 'Human',
    gender: 'M',
    height: 0,
    weight: 0,
    age: 0,
    className: 'Fighter',
    alignment: 'none',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0,
    availableAlignments: [
      'Lawful Good', 'Lawful Neutral', 'Lawful Evil',
      'Neutral Good', 'True Neutral', 'Neutral Evil',
      'Chaotic Good', 'Chaotic Neutral', 'Chaotic Evil'
    ]
  },
  {
    id: 5,
    name: 'Swift McRunfast',
    completionStep: 5,
    str: 12,
    dex: 12,
    con: 10,
    int: 18,
    wis: 7,
    chr: 15,
    race: 'Human',
    gender: 'F',
    height: 0,
    weight: 0,
    age: 0,
    className: 'Mage',
    alignment: 'Neutral Good',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0
  },
  {
    id: 6,
    name: 'Big McLargeHuge',
    completionStep: 6,
    str: 18,
    dex: 14,
    con: 9,
    int: 16,
    wis: 11,
    chr: 12,
    race: 'Elf',
    gender: 'M',
    height: 60,
    weight: 110,
    age: 110,
    className: 'Fighter',
    alignment: 'Lawful Good',
    paralyze: 14,
    rod: 16,
    petrification: 15,
    breath: 17,
    spell: 17,
    hp: 9,
    moveRate: 12,
    funds: 170
  }
];

export default internalTestData;
