const internalTestData = [
  {
    id: 1,
    name: 'Big McLargeHuge',
    completionStep: 6,
    str: 18,
    dex: 14,
    con: 9,
    int: 16,
    wis: 11,
    chr: 12,
    race: 'Elf',
    gender: 'M',
    height: 60,
    weight: 110,
    age: 110,
    className: 'Fighter',
    alignment: 'Lawful Good',
    paralyze: 14,
    rod: 16,
    petrification: 15,
    breath: 17,
    spell: 17,
    hp: 9,
    moveRate: 12,
    funds: 170
  },
  {
    id: 2,
    name: 'Gristle McThornbody',
    completionStep: 1,
    str: 0,
    dex: 0,
    con: 0,
    int: 0,
    wis: 0,
    chr: 0,
    race: 'none',
    gender: 'n',
    height: 0,
    weight: 0,
    age: 0,
    className: 'none',
    alignment: 'none',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0
  },
  {
    id: 3,
    name: 'Crunch Bonemeal',
    completionStep: 1,
    str: 0,
    dex: 0,
    con: 0,
    int: 0,
    wis: 0,
    chr: 0,
    race: 'none',
    gender: 'n',
    height: 0,
    weight: 0,
    age: 0,
    className: 'none',
    alignment: 'none',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0
  },
  {
    id: 4,
    name: 'Rip Steakface',
    completionStep: 1,
    str: 0,
    dex: 0,
    con: 0,
    int: 0,
    wis: 0,
    chr: 0,
    race: 'none',
    gender: 'n',
    height: 0,
    weight: 0,
    age: 0,
    className: 'none',
    alignment: 'none',
    paralyze: 0,
    rod: 0,
    petrification: 0,
    breath: 0,
    spell: 0,
    hp: 0,
    moveRate: 0,
    funds: 0
  },
  {
    id: 5,
    name: 'Swift McRunfast',
    completionStep: 6,
    str: 12,
    dex: 12,
    con: 10,
    int: 18,
    wis: 7,
    chr: 15,
    race: 'Human',
    gender: 'F',
    height: 65,
    weight: 110,
    age: 18,
    className: 'Mage',
    alignment: 'Neutral Good',
    paralyze: 14,
    rod: 11,
    petrification: 13,
    breath: 15,
    spell: 12,
    hp: 4,
    moveRate: 12,
    funds: 50
  }
];

export default internalTestData;
